'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace Token
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RespuestaToken", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioToken"),  _
     System.SerializableAttribute()>  _
    Partial Public Class RespuestaToken
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private m_ResultadoField As Token.RespuestaToken.TipoResultado
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property m_Resultado() As Token.RespuestaToken.TipoResultado
            Get
                Return Me.m_ResultadoField
            End Get
            Set
                If (Me.m_ResultadoField.Equals(value) <> true) Then
                    Me.m_ResultadoField = value
                    Me.RaisePropertyChanged("m_Resultado")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
        
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
         System.Runtime.Serialization.DataContractAttribute(Name:="RespuestaToken.TipoResultado", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioToken")>  _
        Public Enum TipoResultado As Integer
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            None = 0
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB001_Cliente_enrolado_en_el_sistema = 1
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB002_Cliente_autenticado = 2
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB003_Cliente_no_autenticado = 3
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB004_Usuario_validado_en_el_sistema = 4
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB005_Cliente_eliminado_del_sistema = 5
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB006_Validación_de_usuario_fallida = 6
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB007_Número_de_intentos_de_login_superados = 7
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB008_Excepción_en_parámetros_de_entrada = 8
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB009_Lector_de_huellas_no_conectado = 9
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB010_Excepción_en_la_captura_de_huella = 10
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB011_Falló_en_lector_de_huella = 11
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB012_Huella_ya_capturada_en_el_proceso_de_enrolamiento = 12
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB013_Cámara_web_no_conectada = 13
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB014_Falló_en_cámara_web = 14
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB015_Excepción_en_la_captura_de_foto = 15
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB016_Token_generado_correctamente = 16
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB017_Excepción_de_procesamiento_módulo_central = 17
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB018_Excepción_generado_token = 18
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB019_Consulta_de_token_valido = 19
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB020_Consulta_de_token_invalido = 20
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB021_Excepción_en_generación_de_reporte = 21
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB022_Usuario_creado_correctamente = 22
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB023_Usuario_eliminado = 23
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB024_Perfil_creado = 24
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB025_Perfil_editado = 25
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB026_Tiempo_de_espera_agotado_de_procesamiento = 26
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB027_Cliente_ya_enrolado_en_el_sistema = 27
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB028_Cliente_no_enrolado_en_el_sistema = 28
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB029_Cliente_sin_huellas = 29
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB030_Proceso_Cancelado = 30
        End Enum
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="Token.IToken")>  _
    Public Interface IToken
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IToken/ConsultarToken", ReplyAction:="http://tempuri.org/IToken/ConsultarTokenResponse")>  _
        Function ConsultarToken(ByVal value As String) As Token.RespuestaToken
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ITokenChannel
        Inherits Token.IToken, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class TokenClient
        Inherits System.ServiceModel.ClientBase(Of Token.IToken)
        Implements Token.IToken
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ConsultarToken(ByVal value As String) As Token.RespuestaToken Implements Token.IToken.ConsultarToken
            Return MyBase.Channel.ConsultarToken(value)
        End Function
    End Class
End Namespace
