'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ServiceReferenceBio
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Solicitud", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBiometrico472"),  _
     System.SerializableAttribute()>  _
    Partial Friend Class Solicitud
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private m_Codigo_EntidadField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private m_Codigo_OficinaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private m_Codigo_ServicioField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private m_FotoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private m_HuellasField() As ServiceReferenceBio.Huella
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private m_NI_ClienteField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private m_NI_UsuarioField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private m_TI_ClienteField As ServiceReferenceBio.Solicitud.TipoDocumento
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private m_TI_UsuarioField As ServiceReferenceBio.Solicitud.TipoDocumento
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private m_Tipo_SolicitudField As ServiceReferenceBio.Solicitud.Tipo_Solicitud
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private m__DescripcionField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private m__EventoField As ServiceReferenceBio._Evento
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Friend Property m_Codigo_Entidad() As Integer
            Get
                Return Me.m_Codigo_EntidadField
            End Get
            Set
                If (Me.m_Codigo_EntidadField.Equals(value) <> true) Then
                    Me.m_Codigo_EntidadField = value
                    Me.RaisePropertyChanged("m_Codigo_Entidad")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Friend Property m_Codigo_Oficina() As String
            Get
                Return Me.m_Codigo_OficinaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.m_Codigo_OficinaField, value) <> true) Then
                    Me.m_Codigo_OficinaField = value
                    Me.RaisePropertyChanged("m_Codigo_Oficina")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Friend Property m_Codigo_Servicio() As Integer
            Get
                Return Me.m_Codigo_ServicioField
            End Get
            Set
                If (Me.m_Codigo_ServicioField.Equals(value) <> true) Then
                    Me.m_Codigo_ServicioField = value
                    Me.RaisePropertyChanged("m_Codigo_Servicio")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Friend Property m_Foto() As String
            Get
                Return Me.m_FotoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.m_FotoField, value) <> true) Then
                    Me.m_FotoField = value
                    Me.RaisePropertyChanged("m_Foto")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Friend Property m_Huellas() As ServiceReferenceBio.Huella()
            Get
                Return Me.m_HuellasField
            End Get
            Set
                If (Object.ReferenceEquals(Me.m_HuellasField, value) <> true) Then
                    Me.m_HuellasField = value
                    Me.RaisePropertyChanged("m_Huellas")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Friend Property m_NI_Cliente() As String
            Get
                Return Me.m_NI_ClienteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.m_NI_ClienteField, value) <> true) Then
                    Me.m_NI_ClienteField = value
                    Me.RaisePropertyChanged("m_NI_Cliente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Friend Property m_NI_Usuario() As String
            Get
                Return Me.m_NI_UsuarioField
            End Get
            Set
                If (Object.ReferenceEquals(Me.m_NI_UsuarioField, value) <> true) Then
                    Me.m_NI_UsuarioField = value
                    Me.RaisePropertyChanged("m_NI_Usuario")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Friend Property m_TI_Cliente() As ServiceReferenceBio.Solicitud.TipoDocumento
            Get
                Return Me.m_TI_ClienteField
            End Get
            Set
                If (Me.m_TI_ClienteField.Equals(value) <> true) Then
                    Me.m_TI_ClienteField = value
                    Me.RaisePropertyChanged("m_TI_Cliente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Friend Property m_TI_Usuario() As ServiceReferenceBio.Solicitud.TipoDocumento
            Get
                Return Me.m_TI_UsuarioField
            End Get
            Set
                If (Me.m_TI_UsuarioField.Equals(value) <> true) Then
                    Me.m_TI_UsuarioField = value
                    Me.RaisePropertyChanged("m_TI_Usuario")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Friend Property m_Tipo_Solicitud() As ServiceReferenceBio.Solicitud.Tipo_Solicitud
            Get
                Return Me.m_Tipo_SolicitudField
            End Get
            Set
                If (Me.m_Tipo_SolicitudField.Equals(value) <> true) Then
                    Me.m_Tipo_SolicitudField = value
                    Me.RaisePropertyChanged("m_Tipo_Solicitud")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Friend Property m__Descripcion() As Integer
            Get
                Return Me.m__DescripcionField
            End Get
            Set
                If (Me.m__DescripcionField.Equals(value) <> true) Then
                    Me.m__DescripcionField = value
                    Me.RaisePropertyChanged("m__Descripcion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Friend Property m__Evento() As ServiceReferenceBio._Evento
            Get
                Return Me.m__EventoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.m__EventoField, value) <> true) Then
                    Me.m__EventoField = value
                    Me.RaisePropertyChanged("m__Evento")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
        
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
         System.Runtime.Serialization.DataContractAttribute(Name:="Solicitud.TipoDocumento", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBiometrico472")>  _
        Friend Enum TipoDocumento As Integer
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            CC = 0
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            CE = 1
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            TI = 2
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            RC = 3
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            TE = 4
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            NIT = 5
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            PS = 6
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            DEE = 7
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            OT = 8
        End Enum
        
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
         System.Runtime.Serialization.DataContractAttribute(Name:="Solicitud.Tipo_Solicitud", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBiometrico472")>  _
        Friend Enum Tipo_Solicitud As Integer
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            Enrolamiento = 1
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            Autenticacion = 2
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            Eliminacion = 3
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            Evento = 4
        End Enum
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="_Evento", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBiometrico472"),  _
     System.SerializableAttribute()>  _
    Partial Friend Class _Evento
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EventoField As ServiceReferenceBio._Evento.Tipo_Evento
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MensajeField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Friend Property Evento() As ServiceReferenceBio._Evento.Tipo_Evento
            Get
                Return Me.EventoField
            End Get
            Set
                If (Me.EventoField.Equals(value) <> true) Then
                    Me.EventoField = value
                    Me.RaisePropertyChanged("Evento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Friend Property Mensaje() As String
            Get
                Return Me.MensajeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MensajeField, value) <> true) Then
                    Me.MensajeField = value
                    Me.RaisePropertyChanged("Mensaje")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
        
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
         System.Runtime.Serialization.DataContractAttribute(Name:="_Evento.Tipo_Evento", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBiometrico472")>  _
        Friend Enum Tipo_Evento As Integer
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            None = 0
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB001_Cliente_enrolado_en_el_sistema = 1
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB002_Cliente_autenticado = 2
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB003_Cliente_no_autenticado = 3
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB004_Usuario_validado_en_el_sistema = 4
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB005_Cliente_eliminado_del_sistema = 5
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB006_Validación_de_usuario_fallida = 6
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB007_Número_de_intentos_de_login_superados = 7
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB008_Excepción_en_parámetros_de_entrada = 8
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB009_Lector_de_huellas_no_conectado = 9
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB010_Excepción_en_la_captura_de_huella = 10
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB011_Falló_en_lector_de_huella = 11
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB012_Huella_ya_capturada_en_el_proceso_de_enrolamiento = 12
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB013_Cámara_web_no_conectada = 13
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB014_Falló_en_cámara_web = 14
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB015_Excepción_en_la_captura_de_foto = 15
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB016_Token_generado_correctamente = 16
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB017_Excepción_de_procesamiento_módulo_central = 17
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB018_Excepción_generado_token = 18
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB019_Consulta_de_token_valido = 19
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB020_Consulta_de_token_invalido = 20
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB021_Excepción_en_generación_de_reporte = 21
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB022_Usuario_creado_correctamente = 22
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB023_Usuario_eliminado = 23
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB024_Perfil_creado = 24
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB025_Perfil_editado = 25
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB026_Tiempo_de_espera_agotado_de_procesamiento = 26
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB027_Cliente_ya_enrolado_en_el_sistema = 27
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB028_Cliente_no_enrolado_en_el_sistema = 28
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB029_Cliente_sin_huellas = 29
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB030_Proceso_Cancelado = 30
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB031_Perfil_Eliminado = 31
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            SB032_Usuario_Editado = 32
        End Enum
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Huella", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBiometrico472"),  _
     System.SerializableAttribute()>  _
    Partial Friend Class Huella
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DatosField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FormatoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HuellaIDField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Friend Property Datos() As String
            Get
                Return Me.DatosField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DatosField, value) <> true) Then
                    Me.DatosField = value
                    Me.RaisePropertyChanged("Datos")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Friend Property Formato() As String
            Get
                Return Me.FormatoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FormatoField, value) <> true) Then
                    Me.FormatoField = value
                    Me.RaisePropertyChanged("Formato")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Friend Property HuellaID() As String
            Get
                Return Me.HuellaIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.HuellaIDField, value) <> true) Then
                    Me.HuellaIDField = value
                    Me.RaisePropertyChanged("HuellaID")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RespuestaSolicitud", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBiometrico472"),  _
     System.SerializableAttribute()>  _
    Partial Friend Class RespuestaSolicitud
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private m_ResultadoField As ServiceReferenceBio.RespuestaSolicitud.TipoResultado
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private m_TokenField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private m__EventoField As ServiceReferenceBio._Evento
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Friend Property m_Resultado() As ServiceReferenceBio.RespuestaSolicitud.TipoResultado
            Get
                Return Me.m_ResultadoField
            End Get
            Set
                If (Me.m_ResultadoField.Equals(value) <> true) Then
                    Me.m_ResultadoField = value
                    Me.RaisePropertyChanged("m_Resultado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Friend Property m_Token() As String
            Get
                Return Me.m_TokenField
            End Get
            Set
                If (Object.ReferenceEquals(Me.m_TokenField, value) <> true) Then
                    Me.m_TokenField = value
                    Me.RaisePropertyChanged("m_Token")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Friend Property m__Evento() As ServiceReferenceBio._Evento
            Get
                Return Me.m__EventoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.m__EventoField, value) <> true) Then
                    Me.m__EventoField = value
                    Me.RaisePropertyChanged("m__Evento")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
        
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
         System.Runtime.Serialization.DataContractAttribute(Name:="RespuestaSolicitud.TipoResultado", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBiometrico472")>  _
        Friend Enum TipoResultado As Integer
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            Proceso_Correcto = 0
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            Proceso_Fallido = 1
        End Enum
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SolicitudParametrizacion", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBiometrico472"),  _
     System.SerializableAttribute()>  _
    Partial Friend Class SolicitudParametrizacion
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DataField() As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private m_NIField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private m_TIField As ServiceReferenceBio.SolicitudParametrizacion.TipoDocumento
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private m_Tipo_SolicitudField As ServiceReferenceBio.SolicitudParametrizacion.Tipo_Solicitud
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Friend Property Data() As String()
            Get
                Return Me.DataField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DataField, value) <> true) Then
                    Me.DataField = value
                    Me.RaisePropertyChanged("Data")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Friend Property m_NI() As String
            Get
                Return Me.m_NIField
            End Get
            Set
                If (Object.ReferenceEquals(Me.m_NIField, value) <> true) Then
                    Me.m_NIField = value
                    Me.RaisePropertyChanged("m_NI")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Friend Property m_TI() As ServiceReferenceBio.SolicitudParametrizacion.TipoDocumento
            Get
                Return Me.m_TIField
            End Get
            Set
                If (Me.m_TIField.Equals(value) <> true) Then
                    Me.m_TIField = value
                    Me.RaisePropertyChanged("m_TI")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Friend Property m_Tipo_Solicitud() As ServiceReferenceBio.SolicitudParametrizacion.Tipo_Solicitud
            Get
                Return Me.m_Tipo_SolicitudField
            End Get
            Set
                If (Me.m_Tipo_SolicitudField.Equals(value) <> true) Then
                    Me.m_Tipo_SolicitudField = value
                    Me.RaisePropertyChanged("m_Tipo_Solicitud")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
        
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
         System.Runtime.Serialization.DataContractAttribute(Name:="SolicitudParametrizacion.TipoDocumento", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBiometrico472")>  _
        Friend Enum TipoDocumento As Integer
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            CC = 0
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            CE = 1
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            TI = 2
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            RC = 3
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            TE = 4
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            NIT = 5
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            PS = 6
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            DEE = 7
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            OT = 8
        End Enum
        
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
         System.Runtime.Serialization.DataContractAttribute(Name:="SolicitudParametrizacion.Tipo_Solicitud", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBiometrico472")>  _
        Friend Enum Tipo_Solicitud As Integer
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            Enrolamiento = 1
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            Autenticacion = 2
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            Validacion = 3
        End Enum
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RespuestaParametrizacion", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBiometrico472"),  _
     System.SerializableAttribute()>  _
    Partial Friend Class RespuestaParametrizacion
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CalidadField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DataField() As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private H_AutenticacionField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private H_EnrolamientoField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private m__EventoField As ServiceReferenceBio._Evento
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Friend Property Calidad() As Integer
            Get
                Return Me.CalidadField
            End Get
            Set
                If (Me.CalidadField.Equals(value) <> true) Then
                    Me.CalidadField = value
                    Me.RaisePropertyChanged("Calidad")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Friend Property Data() As String()
            Get
                Return Me.DataField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DataField, value) <> true) Then
                    Me.DataField = value
                    Me.RaisePropertyChanged("Data")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Friend Property H_Autenticacion() As Integer
            Get
                Return Me.H_AutenticacionField
            End Get
            Set
                If (Me.H_AutenticacionField.Equals(value) <> true) Then
                    Me.H_AutenticacionField = value
                    Me.RaisePropertyChanged("H_Autenticacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Friend Property H_Enrolamiento() As Integer
            Get
                Return Me.H_EnrolamientoField
            End Get
            Set
                If (Me.H_EnrolamientoField.Equals(value) <> true) Then
                    Me.H_EnrolamientoField = value
                    Me.RaisePropertyChanged("H_Enrolamiento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Friend Property m__Evento() As ServiceReferenceBio._Evento
            Get
                Return Me.m__EventoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.m__EventoField, value) <> true) Then
                    Me.m__EventoField = value
                    Me.RaisePropertyChanged("m__Evento")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReferenceBio.IServicioBiometrico")>  _
    Friend Interface IServicioBiometrico
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicioBiometrico/RegistrarProceso", ReplyAction:="http://tempuri.org/IServicioBiometrico/RegistrarProcesoResponse")>  _
        Function RegistrarProceso(ByVal value As ServiceReferenceBio.Solicitud) As ServiceReferenceBio.RespuestaSolicitud
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicioBiometrico/Parametrizacion", ReplyAction:="http://tempuri.org/IServicioBiometrico/ParametrizacionResponse")>  _
        Function Parametrizacion(ByVal value As ServiceReferenceBio.SolicitudParametrizacion) As ServiceReferenceBio.RespuestaParametrizacion
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Friend Interface IServicioBiometricoChannel
        Inherits ServiceReferenceBio.IServicioBiometrico, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Friend Class ServicioBiometricoClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReferenceBio.IServicioBiometrico)
        Implements ServiceReferenceBio.IServicioBiometrico
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function RegistrarProceso(ByVal value As ServiceReferenceBio.Solicitud) As ServiceReferenceBio.RespuestaSolicitud Implements ServiceReferenceBio.IServicioBiometrico.RegistrarProceso
            Return MyBase.Channel.RegistrarProceso(value)
        End Function
        
        Public Function Parametrizacion(ByVal value As ServiceReferenceBio.SolicitudParametrizacion) As ServiceReferenceBio.RespuestaParametrizacion Implements ServiceReferenceBio.IServicioBiometrico.Parametrizacion
            Return MyBase.Channel.Parametrizacion(value)
        End Function
    End Class
End Namespace
